"""add id column to join table

Revision ID: 39926cba26e9
Revises: 998ca822b2fd
Create Date: 2024-03-19 09:46:09.439892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39926cba26e9'
down_revision = '998ca822b2fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_users', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
