"""add autogenerate to id column to join table

Revision ID: f14a7633a2f3
Revises: 08f23bb04501
Create Date: 2024-03-19 10:04:02.149085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14a7633a2f3'
down_revision = '08f23bb04501'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False, autoincrement=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_users', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
